<?php
$headersList = array(
	'CONTINUE' => array('code' => '100', 'message' => 'Continue'),
	'SWITCH' => array('code' => '101', 'message' => 'Switching Protocols'),
	'OK' => array('code' => '200', 'message' => 'OK'),
	'CREATED' => array('code' => '201', 'message' => 'Created'),
	'ACCEPTED' => array('code' => '202', 'message' => 'Accepted'),
	'NON_AUTH' => array('code' => '203', 'message' => 'Non-Authoritative Information'),
	'NO_CONTENT' => array('code' => '204', 'message' => 'No Content'),
	'RESET' => array('code' => '205', 'message' => 'Reset Content'),
	'PARTIAL' => array('code' => '206', 'message' => 'Partial Content'),
	'MULTIPLE' => array('code' => '300', 'message' => 'Multiple Choices'),
	'MOVED_PERM' => array('code' => '301', 'message' => 'Moved Permanently'),
	'MOVED_TEMP' => array('code' => '302', 'message' => 'Moved Temporarily'),
	'SEE_OTHER' => array('code' => '303', 'message' => 'See Other'),
	'NOT_MODIFIED' => array('code' => '304', 'message' => 'Not Modified'),
	'PROXY' => array('code' => '305', 'message' => 'Use Proxy'),
	'BAD_REQUEST' => array('code' => '400', 'message' => 'Bad Request'),
	'UNAUTH' => array('code' => '401', 'message' => 'Unauthorized'),
	'PAYMENT' => array('code' => '402', 'message' => 'Payment Required'),
	'FORBIDDEN' => array('code' => '403', 'message' => 'Forbidden'),
	'NOT_FOUND' => array('code' => '404', 'message' => 'Not Found'),
	'NOT_ALLOWED' => array('code' => '405', 'message' => 'Method Not Allowed'),
	'NOT_ACCEPT' => array('code' => '406', 'message' => 'Not Acceptable'),
	'PROXY_AUTH' => array('code' => '407', 'message' => 'Proxy Authentication Required'),
	'TIMEOUT' => array('code' => '408', 'message' => 'Request Time-out'),
	'CONFLICT' => array('code' => '409', 'message' => 'Conflict'),
	'GONE' => array('code' => '410', 'message' => 'Gone'),
	'LENGTH' => array('code' => '411', 'message' => 'Length Required'),
	'PRE_FAIL' => array('code' => '412', 'message' => 'Precondition Failed'),
	'TOO_LARGE' => array('code' => '413', 'message' => 'Request Entity Too Large'),
	'URI_TOO_LARGE' => array('code' => '414', 'message' => 'Request-URI Too Large'),
	'NOT_SUPPORTED' => array('code' => '415', 'message' => 'Unsupported Media Type'),
	'INTERNAL_ERROR' => array('code' => '500', 'message' => 'Internal Server Error'),
	'NOT_IMPLEMENT' => array('code' => '501', 'message' => 'Not Implemented'),
	'BAD_GATEWAY' => array('code' => '502', 'message' => 'Bad Gateway'),
	'UNAVAILABLE' => array('code' => '503', 'message' => 'Service Unavailable'),
	'GATEWAY_TIMEOUT' => array('code' => '504', 'message' => 'Gateway Time-out'),
	'HTTP_NOT_SUPPORTED' => array('code' => '505', 'message' => 'HTTP Version not supported')
	);
?>